name: 'Soteria'
description: 'Send the repo to soteria server for the security audit'
inputs:
  soteria-token:
    description: 'The token (same as the invitation code) that Soteria has provided to the user'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'